name: Build nightly

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Make application
        run: |
          make
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: FastVideoDS.nds
