name: Build release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make application
        run: |
          make
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp -f FastVideoDS.nds ~/artifacts/
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            FastVideoDS.nds
